baseURL = "https://jdziat.github.io/simple-durable-jobs/"
languageCode = "en-us"
title = "Simple Durable Jobs"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[[menu.main]]
  name = "Documentation"
  pageRef = "/docs"
  weight = 1

[[menu.main]]
  name = "Examples"
  url = "https://github.com/jdziat/simple-durable-jobs/tree/main/examples"
  weight = 2

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/jdziat/simple-durable-jobs"
  weight = 3
  [menu.main.params]
    icon = "github"
