baseURL = "https://jdziat.github.io/simple-durable-jobs/"
title = "Simple Durable Jobs"
theme = "hugo-book"

[params]
  BookRepo = "https://github.com/jdziat/simple-durable-jobs"
  BookSection = "docs"
  BookSearch = true
  BookToC = true
  BookEditPath = "edit/main/docs/content"

[markup]
  [markup.highlight]
    style = "github"
    lineNos = false
  [markup.goldmark.renderer]
    unsafe = true
